import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { Sidebar } from '../../../../components';
import { collection, onSnapshot } from 'firebase/firestore';
import { db } from '../../../../firebase';
import { useRouter } from 'next/router';

const Tests = () => {
  const [questions, setQuestions] = useState([]);

  const questColl = collection(db, `question`);

  const [searchTerm, setSearchTerm] = useState('');

  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    onSnapshot(questColl, (snapshot) =>
      setQuestions(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })))
    );
  }, []);

  return (
    <div>
      <Head>
        <title>edTeach - Kurslar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar>
        <div className="container mx-auto">
          <div className="w-full flex justify-center mt-20">
            <input
              type="text"
              placeholder="enter search term ....."
              className="w-96 py-2 px-5 border border-gray-500  outline-gray-700 "
              onChange={(event) => {
                setSearchTerm(event.target.value);
              }}
            />
          </div>

          {questions
            .filter((val) => {
              if (searchTerm === '') {
                return val;
              } else if (
                val.title
                  .toLocaleLowerCase()
                  .includes(searchTerm.toLocaleLowerCase())
              ) {
                return val;
              }
            })
            .map((val, key) => {
              console.log(id);
              return (
                <>
                  <Link
                    href="/dashboard/question/[id]/[tests]"
                    as={`/dashboard/question/${id}/${val.id}`}
                  >
                    <div
                      key={key}
                      className="w-full rounded-2xl bg-gray-700 text-white p-5 my-3 flex justify-around"
                    >
                      <p>{val.title}</p>
                      <p>{val.description} </p>
                    </div>
                  </Link>
                </>
              );
            })}
        </div>
      </Sidebar>
    </div>
  );
};

export default Tests;
