import { useState, useEffect } from 'react';
import Head from 'next/head';

import { Navbar, Header, About, Feature, Service, Faq, Blog, Price, Contact, Footer, Doc } from 'components';

export default function Home() {
  const [mounted, setMounted] = useState(false);

  // When mounted on client, now we can show the UI
  useEffect(() => setMounted(true), []);

  if (!mounted) return null;
  return (
    <div>
      <Head>
        <title>Ed Teach</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Header />
        <Feature />
        <About />
        <Service/>
        <Blog/>
        <Price />
        <Faq/>
        <Contact />
        <Footer />
      </main>
    </div>
  );
}
