import React from "react";
import Head from "next/head";

const Course = () => {
  return (
    <div>
      <Head>
        <title>edTeach - Kurslar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Course
    </div>
  );
};

export default Course;
