import React, { useEffect, useState } from 'react';
import Head from 'next/head';

import { Sidebar, Breadcrumb } from '../../components';
import { collection, onSnapshot } from 'firebase/firestore';
import { db } from '../../firebase';

const Tests = () => {
  const [questions, setQuestions] = useState([]);

  const questColl = collection(db, `question`);

  const [searchTerm, setSearchTerm] = useState('');
  console.log(questions);
  useEffect(() => {
    onSnapshot(questColl, (snapshot) =>
      setQuestions(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })))
    );
  }, []);

  return (
    <div>
      <Head>
        <title>edTeach - Kurslar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar>
        <Breadcrumb
          page="Asosiy sahifa"
          page2="Umumiy Testlar"
          link="/dashboard"
          active
        />
        <div className="w-full">
          <input
            type="text"
            placeholder="enter search term ....."
            className="px-10 py-5"
            onChange={(event) => {
              setSearchTerm(event.target.value);
            }}
          />

          {questions
            .filter((val) => {
              if (searchTerm === '') {
                return val;
              } else if (
                val.title
                  .toLocaleLowerCase()
                  .includes(searchTerm.toLocaleLowerCase())
              ) {
                return val;
              }
            })
            .map((val, key) => {
              return (
                <div key={key}>
                  <p>{val.title}</p>
                </div>
              );
            })}
        </div>
      </Sidebar>
    </div>
  );
};

export default Tests;
