import React from "react";
import Head from "next/head";

import { Sidebar } from "../../components";

const Tests = () => {
  return (
    <div>
      <Head>
        <title>edTeach - Kurslar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar>
        <div className="p-5">This is a Tests page</div>
      </Sidebar>
    </div>
  );
};

export default Tests;
